'use strict';

// prettier-ignore
const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const form = document.querySelector('.form');
const containerWorkouts = document.querySelector('.workouts');
const inputType = document.querySelector('.form__input--type');
const inputDistance = document.querySelector('.form__input--distance');
const inputDuration = document.querySelector('.form__input--duration');
const inputCadence = document.querySelector('.form__input--cadence');
const inputElevation = document.querySelector('.form__input--elevation');

let map, mapEvent;

// trying navigator
if (navigator.geolocation){
    navigator.geolocation.getCurrentPosition(function(position){
        const  {latitude, longitude} = position.coords;
        console.log(`https://www.google.com/maps/@${latitude},${longitude},15z`);
        
        // trying Leaflet library for map
        const coords = [latitude, longitude];
        map = L.map('map').setView(coords, 13);

        // the map is made from tileLayers. OpenStreetMap is basically a open source map that everyone can use for free
        // https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'   we can change styles by changing this urls available
        L.tileLayer('https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);

        // using event listeners on map, we have to use the map object generated by leaflet to get the coordinates
        // Handling clicks  on map
        map.on('click', function(mapE){
            mapEvent = mapE;
            form.classList.remove('hidden');
            inputDistance.focus();

        });

        
    }, function(){
        alert("Location access denied!");
    });
    
};

// making the form submit the market on the map
form.addEventListener('submit', function(e){
    e.preventDefault();
    // clearing input fields and hiding form
    inputDistance.value = inputDuration.value = inputCadence.value = inputElevation.value = "";
    
    // Display marker
    const {lat, lng} = mapEvent.latlng;
    L.marker([lat, lng])
        .addTo(map)
        .bindPopup(L.popup({
            maxWidth : 250,
            minWidth : 100,
            autoClose : false,
            closeOnClick : false,
            className : 'running-popup',
        }))
        .setPopupContent('Workout')
        .openPopup();

    // form.classList.add('hidden');
});


// changing cadence and elevation based on type
inputType.addEventListener('change', function(){
    inputCadence.closest('.form__row').classList.toggle('form__row--hidden');    
    inputElevation.closest('.form__row').classList.toggle('form__row--hidden');    
});


